baseurl = "https://hrjn.github.io"
title = "H's blog"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 10

pygmentsstyle = "lovelace"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true


[params]
  #author = "Harizo Rajaona"
  info = "Where learnings and tinkerings are written down"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.png"

  favicon_32 = "/images/favicon-32x32.ico"
  favicon_16 = "/images/favicon-16x16.ico"

  since = 2022

  enableTwemoji = true

  colorScheme = "light"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/hrjn/"

[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weigt = 1
  url = "https://www.linkedin.com/in/harizorajaona/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

